// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// shiftCircular
arma::imat shiftCircular(arma::ivec X, arma::ivec Neighbors);
RcppExport SEXP toom_shiftCircular(SEXP XSEXP, SEXP NeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::ivec >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::ivec >::type Neighbors(NeighborsSEXP);
    __result = Rcpp::wrap(shiftCircular(X, Neighbors));
    return __result;
END_RCPP
}
// grid_simulation
Rcpp::DataFrame grid_simulation(int threads, double step, int initial_block_lenght, int max_iterations, int line_size, IntegerVector Neighbors);
RcppExport SEXP toom_grid_simulation(SEXP threadsSEXP, SEXP stepSEXP, SEXP initial_block_lenghtSEXP, SEXP max_iterationsSEXP, SEXP line_sizeSEXP, SEXP NeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type threads(threadsSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< int >::type initial_block_lenght(initial_block_lenghtSEXP);
    Rcpp::traits::input_parameter< int >::type max_iterations(max_iterationsSEXP);
    Rcpp::traits::input_parameter< int >::type line_size(line_sizeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Neighbors(NeighborsSEXP);
    __result = Rcpp::wrap(grid_simulation(threads, step, initial_block_lenght, max_iterations, line_size, Neighbors));
    return __result;
END_RCPP
}
