// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// shiftCircular
NumericMatrix shiftCircular(NumericVector X, IntegerVector Neighbors);
RcppExport SEXP toom_shiftCircular(SEXP XSEXP, SEXP NeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Neighbors(NeighborsSEXP);
    __result = Rcpp::wrap(shiftCircular(X, Neighbors));
    return __result;
END_RCPP
}
// MatrixSample
NumericMatrix MatrixSample(int n, int k, double p);
RcppExport SEXP toom_MatrixSample(SEXP nSEXP, SEXP kSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    __result = Rcpp::wrap(MatrixSample(n, k, p));
    return __result;
END_RCPP
}
// VectorSample
NumericVector VectorSample(int n, double p);
RcppExport SEXP toom_VectorSample(SEXP nSEXP, SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    __result = Rcpp::wrap(VectorSample(n, p));
    return __result;
END_RCPP
}
// simIteration
List simIteration(NumericVector X, double Alpha, IntegerVector Neighbors);
RcppExport SEXP toom_simIteration(SEXP XSEXP, SEXP AlphaSEXP, SEXP NeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type Alpha(AlphaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Neighbors(NeighborsSEXP);
    __result = Rcpp::wrap(simIteration(X, Alpha, Neighbors));
    return __result;
END_RCPP
}
// doSim
DataFrame doSim(double AlphaProb, int Replication, int Size, int MaxIterations, double InitialProb, IntegerVector Neighbors);
RcppExport SEXP toom_doSim(SEXP AlphaProbSEXP, SEXP ReplicationSEXP, SEXP SizeSEXP, SEXP MaxIterationsSEXP, SEXP InitialProbSEXP, SEXP NeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type AlphaProb(AlphaProbSEXP);
    Rcpp::traits::input_parameter< int >::type Replication(ReplicationSEXP);
    Rcpp::traits::input_parameter< int >::type Size(SizeSEXP);
    Rcpp::traits::input_parameter< int >::type MaxIterations(MaxIterationsSEXP);
    Rcpp::traits::input_parameter< double >::type InitialProb(InitialProbSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Neighbors(NeighborsSEXP);
    __result = Rcpp::wrap(doSim(AlphaProb, Replication, Size, MaxIterations, InitialProb, Neighbors));
    return __result;
END_RCPP
}
// doSimLast
DataFrame doSimLast(double AlphaProb, int Replication, int Size, int MaxIterations, double InitialProb, IntegerVector Neighbors);
RcppExport SEXP toom_doSimLast(SEXP AlphaProbSEXP, SEXP ReplicationSEXP, SEXP SizeSEXP, SEXP MaxIterationsSEXP, SEXP InitialProbSEXP, SEXP NeighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type AlphaProb(AlphaProbSEXP);
    Rcpp::traits::input_parameter< int >::type Replication(ReplicationSEXP);
    Rcpp::traits::input_parameter< int >::type Size(SizeSEXP);
    Rcpp::traits::input_parameter< int >::type MaxIterations(MaxIterationsSEXP);
    Rcpp::traits::input_parameter< double >::type InitialProb(InitialProbSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Neighbors(NeighborsSEXP);
    __result = Rcpp::wrap(doSimLast(AlphaProb, Replication, Size, MaxIterations, InitialProb, Neighbors));
    return __result;
END_RCPP
}
