# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Circular Shift for Neighbors Matrix
#'
#' Shift a numeric vector by \code{shift}. End components 
#' is feedback into the begining. This will build a 
#' neighbors matrix
#' 
#' @param \code{x} Numeric vector
#' @param \code{Neighbors} Integer vector with neighbors
#' @return Matrix with Circular shifted versions of \code{x} defined by \code{Neighbors}
#' @export
shiftCircular <- function(X, Neighbors) {
    .Call('toom_shiftCircular', PACKAGE = 'toom', X, Neighbors)
}

MatrixSample <- function(n, k, p) {
    .Call('toom_MatrixSample', PACKAGE = 'toom', n, k, p)
}

#' Generate a random integer vector
#' 
#' @param \code{n} Integer
#' @param \code{n} Double
#' @return Random vector
#' @export
VectorSample <- function(n, p) {
    .Call('toom_VectorSample', PACKAGE = 'toom', n, p)
}

#' Do a Simulation Step (Only 3 neighbors...)
#' 
#' @param \code{X} Numeric vector representing a configuration
#' @param \code{Alpha} Probability of change
#' @param \code{Neighbors} Integer vectors of neighbors
#' @return A List with new state and frequency of symbols
#' @export
simIteration <- function(X, Alpha, Neighbors) {
    .Call('toom_simIteration', PACKAGE = 'toom', X, Alpha, Neighbors)
}

#' Do Automata Simulation (F fixed for Ramos & Leite)
#' 
#' @param \code{AlphaProb} Probability of change
#' @param \code{Replications} Number of replications. Default 100
#' @param \code{Size} Number of components in the configuration
#' @param \code{MaxIterations} Default 1000
#' @param \code{InitialProb} Probability for initial configuration
#' @param \code{Neighbors} Integer vectors of neighbors. Defaulf c(-1,0,1)
#' @return A data frame with Size, Replication, Iteration, AlphaProb and Frequency of Symbols
#' @export
doSim <- function(AlphaProb, Replication = 100L, Size = 1000L, MaxIterations = 1000L, InitialProb = 0.5, Neighbors = as.integer( c(-1,0,1))) {
    .Call('toom_doSim', PACKAGE = 'toom', AlphaProb, Replication, Size, MaxIterations, InitialProb, Neighbors)
}

#' Do Automata Simulation (F fixed for Ramos & Leite)
#' 
#' Save the space and temporal mean of configurations.
#' 
#' @param \code{AlphaProb} Probability of change
#' @param \code{Replications} Number of replications. Default 100
#' @param \code{Size} Number of components in the configuration
#' @param \code{MaxIterations} Default 1000
#' @param \code{InitialProb} Probability for initial configuration
#' @param \code{Neighbors} Integer vectors of neighbors. Defaulf c(-1,0,1)
#' @return A data frame with Size, Replication, Iteration, AlphaProb and Frequency of Symbols
#' @export
doSimLast <- function(AlphaProb, Replication, Size = 1000L, MaxIterations = 10000L, InitialProb = 0.5, Neighbors = as.integer( c(-1,0,1))) {
    .Call('toom_doSimLast', PACKAGE = 'toom', AlphaProb, Replication, Size, MaxIterations, InitialProb, Neighbors)
}

