# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SingleCircularShift <- function(x, shift) {
    .Call('toom_SingleCircularShift', PACKAGE = 'toom', x, shift)
}

shiftCircular <- function(X, Neighbors) {
    .Call('toom_shiftCircular', PACKAGE = 'toom', X, Neighbors)
}

MatrixSample <- function(n, k, p) {
    .Call('toom_MatrixSample', PACKAGE = 'toom', n, k, p)
}

VectorSample <- function(n, p) {
    .Call('toom_VectorSample', PACKAGE = 'toom', n, p)
}

simIteration <- function(X, Alpha, Neighbors) {
    .Call('toom_simIteration', PACKAGE = 'toom', X, Alpha, Neighbors)
}

doSim <- function(AlphaProb, Replication, Size = 1000L, MaxIterations = 10000L, InitialProb = 0.5, Neighbors = as.integer( c(-1,0,1))) {
    .Call('toom_doSim', PACKAGE = 'toom', AlphaProb, Replication, Size, MaxIterations, InitialProb, Neighbors)
}

doSimLast <- function(AlphaProb, Replication, Size = 1000L, MaxIterations = 10000L, InitialProb = 0.5, Neighbors = as.integer( c(-1,0,1))) {
    .Call('toom_doSimLast', PACKAGE = 'toom', AlphaProb, Replication, Size, MaxIterations, InitialProb, Neighbors)
}

