# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Circular Shift for Neighbors Matrix
#'
#' Shift a numeric vector by \code{shift}. End components 
#' is feedback into the begining. This will build a 
#' neighbors matrix
#' 
#' @param \code{x} Numeric vector
#' @param \code{Neighbors} Integer vector with neighbors
#' @return Matrix with Circular shifted versions of \code{x} defined by \code{Neighbors}
#' @export
shiftCircular <- function(X, Neighbors) {
    .Call('toom_shiftCircular', PACKAGE = 'toom', X, Neighbors)
}

#' Do Automata Simulation (F with Alpha and Beta fixed for Ramos & Leite 2016)
#' 
#' Save the space and temporal mean of configurations.
#' 
#' @param \code{line_size} Number of components in the configuration
#' @param \code{Step} Alpha and beta increment
#' @param \code{max_iterations} Default 1000
#' @param \code{replications} Default 1000
#' @param \code{initial_block_size} Inital block size. Default 1.
#' @param \code{Neighbors} Integer vectors of neighbors. Defaulf c(-1,0,1)
#' @return Data frame. If all zeros, return 0. If all ones, return 1. If MaxIterations reached, return -1.
#' @export
grid_simulation <- function(threads = 1L, step = 0.01, initial_block_lenght = 1L, max_iterations = 100000L, line_size = 1000L, Neighbors = as.integer( c(-1,0,1))) {
    .Call('toom_grid_simulation', PACKAGE = 'toom', threads, step, initial_block_lenght, max_iterations, line_size, Neighbors)
}

